---
title: "exercise 5"

---
Open Library
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(infer)
```

CHALLENGE 1

Step 1
```{r}
f<- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/IMDB-movies.csv"
d<- read_csv(f, col_names = T)
```

Step 2
```{r}
d<- d|> filter(startYear>= 1920 & startYear<= 1979 & runtimeMinutes>= 60 & runtimeMinutes<= 180) |> mutate(decade = case_when(startYear<1930 ~ "20s", startYear< 1940 ~ "30s", startYear<1950 ~ "40s", startYear<1960 ~ "50s", startYear<1970 ~ "60s", startYear<=1979 ~"70s"))
# first filter removes all years outside of 1920-1979 and anything not between 60 and 180 minutes
# second pipe mutates another column called decade that gives a decade label to each group of startyears
```

Step 3
```{r}
ggplot(data = d, mapping = aes(runtimeMinutes, color = paste(decade))) + geom_histogram(binwidth = 0.5) + facet_wrap(~d$decade)
```
Step 4
```{r}

results<- summarise(group_by(d,d$decade), dmean = mean(runtimeMinutes, na.rm = T), dsd= sd(runtimeMinutes, na.rm = T))
results
```

Step 5
```{r}
samples <- d |> group_by(decade) |> sample_n(100, replace = FALSE) |> ungroup()
samples
samplestats<- summarise(group_by(samples, samples$decade), samplemean = mean(runtimeMinutes, na.rm = T), samplesd = sd(runtimeMinutes, na.rm = T))
samplestats
```

Step 6
```{r}
n<- 100
samplestats<- samplestats|> mutate(sampleSE = samplesd/sqrt(n))
# standard deviation of sample/ sqrt(sample size)
samplestats
```

Step 6.5
```{r}
names(samplestats)[names(samplestats) == "samples$decade"] <- "decade"
names(results)[names(results) == "d$decade"] <- "decade"
# ^ so I can join tables together for convenience
fullstats<- (left_join(samplestats, results, by = "decade"))
fullstats<- rename(fullstats, popmean = dmean)
fullstats<- rename(fullstats, popsd = dsd)
fullstats
# again just to clean up the names for this table
```

Step 7
```{r}
fullstats<- fullstats |> mutate(popSE= popsd/sqrt(n))
fullstats
```

Step 8
```{r}
reps<- 1000

sampdist<- d|> group_by(decade) |> rep_sample_n(size = 100, replace = F, reps = 1000, prob = NULL) 

sampdiststep8<- sampdist|> group_by(replicate, decade) |> summarise(samplemean = mean(runtimeMinutes, na.rm=T), samplesd = sd(runtimeMinutes, na.rm = T))
sampdiststep8

```


Step 9
```{r}
sampdiststatsstep9<- summarise(group_by(sampdist, sampdist$decade), samplemean = mean(runtimeMinutes, na.rm = T), samplesd = sd(runtimeMinutes, na.rm = T))
names(sampdiststatsstep9)[names(sampdiststatsstep9) == "sampdist$decade"] <- "decade"

ggplot(data = sampdiststep8, mapping = aes(samplemean ,color = paste(decade))) + geom_histogram(binwidth = 0.5) + facet_wrap(~sampdiststep8$decade)
```


Step 10
```{r}
#1
mean(samplestats$sampleSE)
#2
mean(fullstats$popSE)
#3
mean(sampdiststatsstep9$samplesd) 
#^ since multiple samples of the same pop were taken we can use the standard deviaiton of the entire distribution
```


CHALLENGE 2

Step 1
```{r}
f<- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/zombies.csv"
z<- read_csv(f, col_names = T)
```


Step 2
```{r}
pmheight<- mean(z$height)
pmweight<- mean(z$weight)
pmage<- mean(z$age)
pmkills<- mean(z$zombies_killed)
pmYoEd<- mean(z$years_of_education)

psdheight<- sdpop(z$height)
psdweight<- sdpop(z$weight)
psdage<- sdpop(z$age)
psdkills<- sdpop(z$zombies_killed)
psdYoEd<- sdpop(z$years_of_education)

```


Step 3
```{r}
hbox<- ggplot(data = z, aes(x = gender, y= height))
hbox<- hbox + geom_boxplot(na.rm = T)
wbox<- ggplot(data = z, aes(x = gender, y= weight))
wbox<- wbox + geom_boxplot(na.rm = T)
abox<- ggplot(data = z, aes(x = gender, y= age))
abox<- abox + geom_boxplot(na.rm = T)
kbox<- ggplot(data = z, aes(x = gender, y= zombies_killed))
kbox<- kbox + geom_boxplot(na.rm = T)
YEbox<- ggplot(data = z, aes(x = gender, y= years_of_education))
YEbox<- YEbox + geom_boxplot(na.rm = T)
```


Step 4
```{r}

Heightagesplot<- ggplot(data = z, aes(x = age, height)) + geom_point(aes(color = factor(gender)), na.rm = T)

Weightagesplot<- ggplot(data = z, aes(x = age, weight)) + geom_point(aes(color = factor(gender)), na.rm = T)

Heightagesplot + Weightagesplot
```


Step 5
```{r}

histogram(z$height)
qqnorm(z$height)
qqline(z$height)
histogram(z$weight)
qqnorm(z$weight)
qqline(z$weight)
histogram(z$zombies_killed)
qqnorm(z$zombies_killed)
qqline(z$zombies_killed)
histogram(z$years_of_education)
qqnorm(z$years_of_education)
qqline(z$years_of_education)
#height and weight appear to be normally distributed while zombies killed and years of education appear to not be normally distributed based on the qqnorm and qqlines
```


Step 6
```{r}
s<- sample_n(z, 50, replace = F)
singlesample<- summarise(s,meanheight= mean(height), sdheight= sd(height),SEheight= sdheight/sqrt(50), meanweight = mean(weight), sdweight= sd(weight),SEweight= sdweight/sqrt(50), meankills= mean(zombies_killed), sdkills= sd(zombies_killed), SEkills= sdkills/sqrt(50), meanYoEd= mean(years_of_education), sdYoEd= sd(years_of_education), SEYoEd= sdYoEd/sqrt(50))

singlesample
t.test(s$weight, mu= 143.9, alternative = "two.sided")
t.test(s$height, mu= mean(z$height), alternative = "two.sided")
t.test(s$zombies_killed, mu= mean(z$zombies_killed), alternative = "two.sided")
t.test(s$years_of_education, mu= mean(z$years_of_education), alternative = "two.sided")

```

Step 7 
```{r}
zampdist<- z |> rep_sample_n(size = 50, replace = F, reps = 199)
zampdiststats<- zampdist|> summarise(meanheight= mean(height), sdheight= sd(height),SEheight= sdheight/sqrt(50), meanweight = mean(weight), sdweight= sd(weight),SEweight= sdweight/sqrt(50), meankills= mean(zombies_killed), sdkills= sd(zombies_killed), SEkills= sdkills/sqrt(50), meanYoEd= mean(years_of_education), sdYoEd= sd(years_of_education), SEYoEd= sdYoEd/sqrt(50))

zampdiststatsMH<- mean(zampdist$height)
zampdiststatsMW<- mean(zampdist$weight)
zampdiststatsMK<- mean(zampdist$zombies_killed)
zampdiststatsMY<- mean(zampdist$years_of_education)
zampdiststatsSDH<- sd(zampdist$height)
zampdiststatsSDW<- sd(zampdist$weight)
zampdiststatsSDK<- sd(zampdist$zombies_killed)
zampdiststatssdY<- sd(zampdist$years_of_education)

```


Step 8
```{r}
histogram(zampdiststats$meanheight)
histogram(zampdiststats$meanweight)
histogram(zampdiststats$meankills)
histogram(zampdiststats$meanYoEd)
qqnorm(zampdiststats$meanYoEd)

# the sampling distributions appear normally distributed even in those that were not originally normally distributed
```


Step 9
```{r}

mhlower<- quantile(zampdiststats$meanheight, 0.025)
mhupper<- quantile(zampdiststats$meanheight, 0.975)
mh_ci<- c(mhlower, mhupper)
mh_ci

mwlower<- quantile(zampdiststats$meanweight, 0.025)
mwupper<- quantile(zampdiststats$meanweight, 0.975)
mw_ci<- c(mwlower, mwupper)
mw_ci

mklower<- quantile(zampdiststats$meankills, 0.025)
mkupper<- quantile(zampdiststats$meankills, 0.975)
mk_ci<- c(mklower, mkupper)
mk_ci

mYlower<- quantile(zampdiststats$meanYoEd, 0.025)
mYupper<- quantile(zampdiststats$meanYoEd, 0.975)
mY_ci<- c(mYlower, mYupper)
mY_ci
```


Step 10
```{r}
#height
n_boot=1000
hboot<- vector(length = n_boot)
n<- length(s) 
for (i in 1:n_boot) {
  hboot[[i]] <- mean(sample(s$height, n, replace = T))
} 
hbootlower<- quantile(hboot, 0.025)
hbootupper<- quantile(hboot, 0.975)
Hci_boot<- c(hbootlower, hbootupper)

#weight
wboot<- vector(length = n_boot)
for (i in 1:n_boot) {
  wboot[[i]] <- mean(sample(s$weight, n, replace = T))
} 
wbootlower<- quantile(wboot, 0.025)
wbootupper<- quantile(wboot, 0.975)
wci_boot<- c(wbootlower, wbootupper)

#zombies killed
kboot<- vector(length = n_boot)
for (i in 1:n_boot) {
  kboot[[i]] <- mean(sample(s$zombies_killed, n, replace = T))
} 
kbootlower<- quantile(kboot, 0.025)
kbootupper<- quantile(kboot, 0.975)
kci_boot<- c(kbootlower, kbootupper)

#years of education
Yboot<- vector(length = n_boot)
for (i in 1:n_boot) {
  Yboot[[i]] <- mean(sample(s$years_of_education, n, replace = T))
} 
Ybootlower<- quantile(Yboot, 0.025)
Ybootupper<- quantile(Yboot, 0.975)
Yci_boot<- c(Ybootlower, Ybootupper)



```